version: "3"
services:
  app:
    container_name: weather_cast_angle_dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4000:4000"
    volumes:
      - ./:/app
    environment:
      OPEN_WEATHER_API_KEY: ${OPEN_WEATHER_API_KEY}
      DATABASE_URL: postgres://postgres:postgres@db/weather_cast_angle_dev_db
    depends_on:
      - db
  db:
    image: postgres:17.4
    container_name: weather_cast_angle_dev_db
    environment:
      # NOTE: docker compose exec db psql -U postgres_dummy_user -W weather_cast_angle_dev_db
      POSTGRES_USER: postgres_dummy_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_DB: weather_cast_angle_dev_db
    ports:
      - "5432:5432"
    volumes:
      - ./db_data_dev:/var/lib/postgresql/data
